### ISSUE TITLE
Binary provenance

### ISSUE THREAD

**Issue by jart** [gnu-enjoyer/ActuallyPortableNim#1]
Hi gnu-enjoyer. Nice project! I was excited to find your blog post here https://mike.fo/blog/nim-is-actually-portable

Could you configure your Makefile to download the amalgamation from https://worker.jart.workers.dev/cosmopolitan-amalgamation-2.0.zip please? That way people will know what version is and where it came from.

Thanks!

**Comment by jart** [comment]
You're also welcome to join our Discord https://discord.gg/tMTyjWrV

**Comment by gnu-enjoyer** [comment]
Gladly, it was on my to-do list but wasn't sure with v2 on the horizon.

**Comment by jart** [comment]
Thank you!
