### ISSUE TITLE
Add link to corresponding blogpost

### ISSUE THREAD

**Issue by PhilippMDoerner** [gnu-enjoyer/ActuallyPortableNim#2]
Heyho, I think for somebody stumbling over the github repo without the context of the blogpost (https://mike.fo/blog/nim-is-actually-portable) it would be nice to see a link to it in the README.md, as said blogpost provides context for the repo as well as a link to the cosmopolitan docs etc.

As a sidenote: The link to the cosmopolitan docs in the blogpost (`https://justine.lol/ape.html.`) is slightly borked, as it has a superfluous `.` at the end leading to a 404 on the justine.lol page.

**Comment by gnu-enjoyer** [comment]
Good idea, the README is a bit terse atm. Will be expanding it now Nim v2 is out.

Appreciate the info about the borked link, fixed thanks Philipp 👍🏻
